# Generated by Django 4.2.9 on 2024-01-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='appform',
            name='branch',
            field=models.ForeignKey(default='l', on_delete=django.db.models.deletion.CASCADE, to='bankapp.branches'),
            preserve_default=False,
        ),
    ]
