# Generated by Django 4.2.9 on 2024-01-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_appform_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appform',
            name='branch',
        ),
    ]
