# Generated by Django 4.2.9 on 2024-01-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_remove_appform_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appform',
        ),
    ]
