# Generated by Django 4.2.9 on 2024-01-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_appform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appform',
        ),
    ]
