# Generated by Django 4.2.9 on 2024-01-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_appform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='district',
        ),
        migrations.DeleteModel(
            name='appform',
        ),
        migrations.DeleteModel(
            name='branches',
        ),
        migrations.DeleteModel(
            name='district',
        ),
    ]
