# Generated by Django 4.2.9 on 2024-01-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0011_appform_acc_type_appform_check_box_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appform',
            old_name='check_box',
            new_name='check_book',
        ),
    ]
