# Generated by Django 4.2.9 on 2024-01-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0013_country_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Branch',
        ),
        migrations.RemoveField(
            model_name='appform',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='appform',
            name='district',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='district',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterField(
            model_name='branch',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='appform',
        ),
        migrations.DeleteModel(
            name='branches',
        ),
    ]
