# Generated by Django 4.2.9 on 2024-01-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0014_rename_city_branch_remove_appform_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='country',
            new_name='branch',
        ),
    ]
