# Generated by Django 4.2.9 on 2024-01-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0015_rename_country_branch_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='district',
        ),
    ]
