# Generated by Django 4.2.9 on 2024-01-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0018_rename_district_district_name_branch_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='District',
        ),
    ]
