# Generated by Django 4.2.9 on 2024-01-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0019_rename_name_branch_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='District',
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bankapp.district'),
            preserve_default=False,
        ),
    ]
