# Generated by Django 4.2.9 on 2024-01-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0020_remove_branch_district_alter_branch_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='name',
        ),
    ]
