# Generated by Django 4.2.9 on 2024-01-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0022_country_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
