# Generated by Django 4.2.9 on 2024-01-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0025_applicationform_delete_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='mail',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
