# Generated by Django 4.2.9 on 2024-01-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0026_applicationform_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='acctype',
            new_name='Date_of_Birth',
        ),
        migrations.RenameField(
            model_name='applicationform',
            old_name='mail',
            new_name='account_ype',
        ),
        migrations.RenameField(
            model_name='applicationform',
            old_name='materials',
            new_name='mail_id',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='dob',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='materials_to_provide',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
